/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, memo, useState } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import * as THREE from 'three';
import { useFrame } from '@react-three/fiber';

const DemoComputer = memo((props) => {
    const group = useRef()
    const screenMeshRef = useRef()
    const { nodes, materials } = useGLTF('/models/computer.glb')
    const [shouldLoadVideo, setShouldLoadVideo] = useState(false)
    const [fadeOpacity, setFadeOpacity] = useState(1)
    const floatOffset = useRef(0)
    
    // Delay video loading to improve initial performance
    useEffect(() => {
        const timer = setTimeout(() => {
            setShouldLoadVideo(true);
        }, 100);
        return () => clearTimeout(timer);
    }, []);
    
    // Load animated video screen textures
    const visuloVideoTexture = useVideoTexture(
        shouldLoadVideo ? '/assets/visulo_video_screen.mp4' : null,
        {
            unsuspend: 'loadstart',
            crossOrigin: 'Anonymous',
            muted: true,
            loop: true,
            start: false
        }
    );
    
    const codeopsVideoTexture = useVideoTexture(
        shouldLoadVideo ? '/assets/codeops_video_screen.mp4' : null,
        {
            unsuspend: 'loadstart',
            crossOrigin: 'Anonymous',
            muted: true,
            loop: true,
            start: false
        }
    );
    
    // Set up video textures
    useEffect(() => {
        if (visuloVideoTexture && shouldLoadVideo) {
            visuloVideoTexture.flipY = false;
            visuloVideoTexture.colorSpace = THREE.SRGBColorSpace;
            // Start video playback
            setTimeout(() => {
                if (visuloVideoTexture.image && visuloVideoTexture.image.play) {
                    visuloVideoTexture.image.play().catch(() => {
                        // Ignore autoplay errors
                    });
                }
            }, 300);
        }
    }, [visuloVideoTexture, shouldLoadVideo]);
    
    useEffect(() => {
        if (codeopsVideoTexture && shouldLoadVideo) {
            codeopsVideoTexture.flipY = false;
            codeopsVideoTexture.colorSpace = THREE.SRGBColorSpace;
            // Start video playback
            setTimeout(() => {
                if (codeopsVideoTexture.image && codeopsVideoTexture.image.play) {
                    codeopsVideoTexture.image.play().catch(() => {
                        // Ignore autoplay errors
                    });
                }
            }, 300);
        }
    }, [codeopsVideoTexture, shouldLoadVideo]);
    
    // Determine current video texture based on logoScreen prop
    const logoPath = props.logoScreen || '/assets/visulo_video_screen.mp4'
    const currentTexture = logoPath.includes('visulo') ? visuloVideoTexture : 
                          logoPath.includes('codeops') ? codeopsVideoTexture : 
                          visuloVideoTexture // fallback
    
    // Determine logo type for animations
    const logoType = logoPath?.includes('visulo') ? 'visulo' : 
                     logoPath?.includes('codeops') ? 'codeops' : 'visulo'

    // Subtle floating animation
    useFrame((state) => {
        if (screenMeshRef.current && currentTexture) {
            // Check for reduced motion preference
            const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches
            
            if (!prefersReducedMotion) {
                // Very subtle float animation
                floatOffset.current = Math.sin(state.clock.elapsedTime * 0.5) * 0.002
                screenMeshRef.current.position.y = 1.831 + floatOffset.current
            }
        }
    })

    // Handle cross-fade animation when switching projects
    useEffect(() => {
        if (screenMeshRef.current?.material && currentTexture) {
            // Brief fade effect when changing videos
            gsap.to(screenMeshRef.current.material, {
                opacity: 0.8,
                duration: 0.2,
                ease: 'power2.out',
                yoyo: true,
                repeat: 1
            })
        }
    }, [currentTexture])

    // Spin animation on texture change
    useGSAP(() => {
        if (group.current) {
            gsap.from(group.current.rotation, {
                y: Math.PI / 2,
                duration: 1,
                ease: 'power3.out'
            })
        }
    }, [currentTexture])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    ref={screenMeshRef}
                    name="monitor-screen"
                    castShadow
                    receiveShadow
                    geometry={nodes['monitor-screen'].geometry}
                    position={[0.127, 1.831, 0.511]}
                    rotation={[1.571, -0.005, 0.031]}
                    scale={[0.661, 0.608, 0.401]}
                >
                    <meshBasicMaterial
                        map={currentTexture}
                        transparent={false}
                        opacity={1.0}
                        toneMapped={false}
                        side={THREE.FrontSide}
                        depthWrite={true}
                    />
                </mesh>
                <group
                    name="RootNode"
                    position={[0, 1.093, 0]}
                    rotation={[-Math.PI / 2, 0, -0.033]}
                    scale={0.045}>
                    {/* Removed 148 empty Screen groups for performance optimization */}
                    <group
                        name="Tower-light-007"
                        position={[16.089, -3.47, -14.495]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.963}
                    />
                    <group
                        name="Tower-light-008"
                        position={[15.155, -3.47, -14.495]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.963}
                    />
                </group>
                <group
                    name="Monitor-B-_computer_0"
                    position={[0.266, 1.132, 0.051]}
                    rotation={[0, -0.033, 0]}
                    scale={[0.042, 0.045, 0.045]}>
                    <mesh
                        name="Monitor-B-_computer_0_1"
                        castShadow
                        receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_1'].geometry}
                        material={materials.computer}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_2"
                        castShadow
                        receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_2'].geometry}
                        material={materials.base__0}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_3"
                        castShadow
                        receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_3'].geometry}
                        material={materials.Material_36}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_4"
                        castShadow
                        receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_4'].geometry}
                        material={materials.Material_35}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_5"
                        castShadow
                        receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_5'].geometry}
                        material={materials.Material_34}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_6"
                        castShadow
                        receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_6'].geometry}
                        material={materials.keys}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_7"
                        castShadow
                        receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_7'].geometry}
                        material={materials.keys2}
                    />
                    <mesh
                        name="Monitor-B-_computer_0_8"
                        castShadow
                        receiveShadow
                        geometry={nodes['Monitor-B-_computer_0_8'].geometry}
                        material={materials.Material_37}
                    />
                </group>
            </group>
        </group>
    )
});

useGLTF.preload('/models/computer.glb')

export default DemoComputer;